public class Test {
public static String render() {
StringBuilder builder = new StringBuilder();
 builder.append("<!DOCTYPE html>\n");
 builder.append("<html>\n");
 builder.append("	<head>\n");
 builder.append("		\n");
 builder.append("		<!-- Basic -->\n");
 builder.append("		<meta charset=\"utf-8\">\n");
 builder.append("		<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
 builder.append("		\n");
 builder.append("		<title>\n");
 builder.append("			Error\n");
 builder.append("		</title>\n");
 builder.append("		\n");
 builder.append("		\n");
 builder.append("		<!-- Mobile Metas -->\n");
 builder.append("		<meta name=\"viewport\" content=\"width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n");
 builder.append("		\n");
 builder.append("		<!-- Web Fonts  -->\n");
 builder.append("		\n");
 builder.append("		\n");
 builder.append("		<!-- Vendor CSS -->\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/vendor/bootstrap/css/bootstrap.css\">\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/vendor/font-awesome/css/font-awesome.css\">\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/vendor/simple-line-icons/css/simple-line-icons.css\">\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/vendor/owl.carousel/assets/owl.carousel.min.css\">\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/vendor/owl.carousel/assets/owl.theme.default.min.css\">\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/vendor/magnific-popup/magnific-popup.css\">\n");
 builder.append("		\n");
 builder.append("		<!-- Theme CSS -->\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/css/theme.css\">\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/css/theme-elements.css\">\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/css/theme-blog.css\">\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/css/theme-shop.css\">\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/css/theme-animate.css\">\n");
 builder.append("		\n");
 builder.append("		<!-- Current Page CSS -->\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/vendor/rs-plugin/css/settings.css\" media=\"screen\">\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/vendor/rs-plugin/css/layers.css\" media=\"screen\">\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/vendor/rs-plugin/css/navigation.css\" media=\"screen\">\n");
 builder.append("		\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/vendor/circle-flip-slideshow/css/component.css\" media=\"screen\">\n");
 builder.append("		\n");
 builder.append("		<!-- Skin CSS -->\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/css/skins/default.css\">\n");
 builder.append("		\n");
 builder.append("		<!-- Theme Custom CSS -->\n");
 builder.append("		<link rel=\"stylesheet\" href=\"/OAS/css/custom.css\">\n");
 builder.append("		\n");
 builder.append("		<!-- Head Libs -->\n");
 builder.append("		<script src=\"/OAS/vendor/modernizr/modernizr.js\">\n");
 builder.append("		</script>\n");
 builder.append("		\n");
 builder.append("		<!--[if IE]>\n");
 builder.append("		    <link rel=\"stylesheet\" href=\"css/ie.css\">\n");
 builder.append("		    <![endif]-->\n");
 builder.append("		\n");
 builder.append("		<!--[if lte IE 8]>\n");
 builder.append("		    <script src=\"vendor/respond/respond.js\"></script>\n");
 builder.append("		    <script src=\"vendor/excanvas/excanvas.js\"></script>\n");
 builder.append("		    <![endif]-->\n");
 builder.append("		\n");
 builder.append("	</head>\n");
 builder.append("	<body>\n");
 builder.append("		\n");
 builder.append("		<div class=\"body coming-soon\">\n");
 builder.append("			\n");
 builder.append("			<div role=\"main\" class=\"main\">\n");
 builder.append("				<div class=\"container\">\n");
 builder.append("					<div class=\"row\">\n");
 builder.append("						<div class=\"col-md-12\">\n");
 builder.append("							<hr class=\"tall\">\n");
 builder.append("						</div>\n");
 builder.append("					</div>\n");
 builder.append("					<div class=\"row\">\n");
 builder.append("						<div class=\"col-md-12 center\">\n");
 builder.append("							<h1 class=\"mb-sm small\">\n");
 builder.append("								Error\n");
 builder.append("							</h1>\n");
 builder.append("							<p class=\"lead\">\n");
 builder.append("								Your account is not verified yet!!\n");
 builder.append("								<br>\n");
 builder.append("								</br>\n");
 builder.append("								Contact administrative staff for further\n");
 builder.append("								information.\n");
 builder.append("							</p>\n");
 builder.append("						</div>\n");
 builder.append("					</div>\n");
 builder.append("					<div class=\"row\">\n");
 builder.append("						<div class=\"col-md-12\">\n");
 builder.append("							<center>\n");
 builder.append("								<a class=\"\" href=\"/OAS/logout\">\n");
 builder.append("									Log Out\n");
 builder.append("								</a>\n");
 builder.append("								 \n");
 builder.append("								<!-- LOG OUT LINK -->\n");
 builder.append("							</center>\n");
 builder.append("						</div>\n");
 builder.append("					</div>\n");
 builder.append("					<div class=\"row\">\n");
 builder.append("						<div class=\"col-md-12\">\n");
 builder.append("							<hr class=\"tall\">\n");
 builder.append("						</div>\n");
 builder.append("					</div>\n");
 builder.append("				</div>\n");
 builder.append("			</div>\n");
 builder.append("			\n");
 builder.append("		</div>\n");
 builder.append("		\n");
 builder.append("		<!-- Vendor -->\n");
 builder.append("		<!--[if lt IE 9]>\n");
 builder.append("		<script src=\"//code.jquery.com/jquery-1.11.3.min.js\"></script>\n");
 builder.append("		<![endif]-->\n");
 builder.append("		<!--[if gte IE 9]><!-->\n");
 builder.append("		<script src=\"/OAS/vendor/jquery/jquery.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<!--<![endif]-->\n");
 builder.append("		<script src=\"/OAS/vendor/jquery.appear/jquery.appear.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/jquery.easing/jquery.easing.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/jquery-cookie/jquery-cookie.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/bootstrap/js/bootstrap.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/common/common.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/jquery.validation/jquery.validation.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/jquery.stellar/jquery.stellar.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/jquery.gmap/jquery.gmap.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/jquery.lazyload/jquery.lazyload.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/isotope/jquery.isotope.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/owl.carousel/owl.carousel.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/magnific-popup/jquery.magnific-popup.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/vide/vide.js\">\n");
 builder.append("		</script>\n");
 builder.append("		\n");
 builder.append("		<!-- Theme Base, Components and Settings -->\n");
 builder.append("		<script src=\"/OAS/js/theme.js\">\n");
 builder.append("		</script>\n");
 builder.append("		\n");
 builder.append("		<!-- Specific Page Vendor and Views -->\n");
 builder.append("		<script src=\"/OAS/vendor/rs-plugin/js/jquery.themepunch.tools.min.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/rs-plugin/js/jquery.themepunch.revolution.min.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/rs-plugin/js/extensions/revolution.extension.actions.min.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/rs-plugin/js/extensions/revolution.extension.carousel.min.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/rs-plugin/js/extensions/revolution.extension.kenburn.min.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/rs-plugin/js/extensions/revolution.extension.layeranimation.min.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/rs-plugin/js/extensions/revolution.extension.migration.min.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/rs-plugin/js/extensions/revolution.extension.navigation.min.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/rs-plugin/js/extensions/revolution.extension.parallax.min.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/rs-plugin/js/extensions/revolution.extension.slideanims.min.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/vendor/rs-plugin/js/extensions/revolution.extension.video.min.js\">\n");
 builder.append("		</script>\n");
 builder.append("		\n");
 builder.append("		<script src=\"/OAS/vendor/circle-flip-slideshow/js/jquery.flipshow.js\">\n");
 builder.append("		</script>\n");
 builder.append("		<script src=\"/OAS/js/views/view.home.js\">\n");
 builder.append("		</script>\n");
 builder.append("		\n");
 builder.append("		<!-- Theme Custom -->\n");
 builder.append("		<script src=\"/OAS/js/custom.js\">\n");
 builder.append("		</script>\n");
 builder.append("		\n");
 builder.append("		<!-- Theme Initialization Files -->\n");
 builder.append("		<script src=\"/OAS/js/theme.init.js\">\n");
 builder.append("		</script>\n");
 builder.append("		\n");
 builder.append("		<!-- Google Analytics: Change UA-XXXXX-X to be your site's ID. Go to http://www.google.com/analytics/ for more information.\n");
 builder.append("		<script type=\"text/javascript\">\n");
 builder.append("		\n");
 builder.append("		    var _gaq = _gaq || [];\n");
 builder.append("		    _gaq.push(['_setAccount', 'UA-12345678-1']);\n");
 builder.append("		    _gaq.push(['_trackPageview']);\n");
 builder.append("		\n");
 builder.append("		    (function() {\n");
 builder.append("		    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\n");
 builder.append("		    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n");
 builder.append("		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\n");
 builder.append("		    })();\n");
 builder.append("		\n");
 builder.append("		</script>\n");
 builder.append("		-->\n");
 builder.append("		\n");
 builder.append("	</body>\n");
 builder.append("</html>\n");
 return builder.toString(); 
 }
}